# Generated by Django 5.0.3 on 2024-03-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileupload',
            name='trained_model_data',
            field=models.BinaryField(null=True),
        ),
    ]
