# Generated by Django 5.0.3 on 2024-03-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_datafileupload_trained_model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileupload',
            name='x_test_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafileupload',
            name='y_test_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
